# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.tmp/axi_hdmi_pixel_buff_v1_1_project/axi_hdmi_pixel_buff_v1_1_project.cache/wt [current_project]
set_property parent.project_path e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.tmp/axi_hdmi_pixel_buff_v1_1_project/axi_hdmi_pixel_buff_v1_1_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/ip_repo/axi_hdmi_pixel_buff_1.1
  e:/ip_repo/hdmi_pixel_gen_1.1_1.0
  e:/ip_repo/test_axi_1.0
  c:/Users
} [current_project]
update_ip_catalog
set_property ip_output_repo e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.tmp/axi_hdmi_pixel_buff_v1_1_project/axi_hdmi_pixel_buff_v1_1_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library "" {
  e:/ip_repo/axi_hdmi_pixel_buff_1.1/hdl/axi_hdmi_pixel_buff_v1_1_HDMI_PIXEL_GEN.v
  e:/ip_repo/axi_hdmi_pixel_buff_1.1/hdl/axi_hdmi_pixel_buff_v1_1.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top axi_hdmi_pixel_buff_v1_1 -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef axi_hdmi_pixel_buff_v1_1.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file axi_hdmi_pixel_buff_v1_1_utilization_synth.rpt -pb axi_hdmi_pixel_buff_v1_1_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
