# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Master.xdc

# Block Designs: bd/spectrum_feb10_xadc_hdmi/spectrum_feb10_xadc_hdmi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spectrum_feb10_xadc_hdmi || ORIG_REF_NAME==spectrum_feb10_xadc_hdmi} -quiet] -quiet

# IP: bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_processing_system7_0_0/spectrum_feb10_xadc_hdmi_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spectrum_feb10_xadc_hdmi_processing_system7_0_0 || ORIG_REF_NAME==spectrum_feb10_xadc_hdmi_processing_system7_0_0} -quiet] -quiet

# IP: bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spectrum_feb10_xadc_hdmi_xadc_wiz_0_0 || ORIG_REF_NAME==spectrum_feb10_xadc_hdmi_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_rgb2dvi_0_0/spectrum_feb10_xadc_hdmi_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spectrum_feb10_xadc_hdmi_rgb2dvi_0_0 || ORIG_REF_NAME==spectrum_feb10_xadc_hdmi_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_clk_wiz_0_0/spectrum_feb10_xadc_hdmi_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spectrum_feb10_xadc_hdmi_clk_wiz_0_0 || ORIG_REF_NAME==spectrum_feb10_xadc_hdmi_clk_wiz_0_0} -quiet] -quiet

# IP: bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xbar_0/spectrum_feb10_xadc_hdmi_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spectrum_feb10_xadc_hdmi_xbar_0 || ORIG_REF_NAME==spectrum_feb10_xadc_hdmi_xbar_0} -quiet] -quiet

# IP: bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_ps7_0_axi_periph_0/spectrum_feb10_xadc_hdmi_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spectrum_feb10_xadc_hdmi_ps7_0_axi_periph_0 || ORIG_REF_NAME==spectrum_feb10_xadc_hdmi_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_rst_ps7_0_50M_0/spectrum_feb10_xadc_hdmi_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spectrum_feb10_xadc_hdmi_rst_ps7_0_50M_0 || ORIG_REF_NAME==spectrum_feb10_xadc_hdmi_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_hdmi_full_gen_1_0_0/spectrum_feb10_xadc_hdmi_hdmi_full_gen_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spectrum_feb10_xadc_hdmi_hdmi_full_gen_1_0_0 || ORIG_REF_NAME==spectrum_feb10_xadc_hdmi_hdmi_full_gen_1_0_0} -quiet] -quiet

# IP: bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_auto_pc_0/spectrum_feb10_xadc_hdmi_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spectrum_feb10_xadc_hdmi_auto_pc_0 || ORIG_REF_NAME==spectrum_feb10_xadc_hdmi_auto_pc_0} -quiet] -quiet

# XDC: bd/spectrum_feb10_xadc_hdmi/spectrum_feb10_xadc_hdmi_ooc.xdc
