# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.cache/wt [current_project]
set_property parent.project_path E:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/ip_repo/hdmi_full_gen_1_1.0
  e:/ip_repo/axi_hdmi_pixel_buff_1.1
  e:/ip_repo/hdmi_pixel_gen_1.1_1.0
  e:/ip_repo/test_axi_1.0
  c:/Users
} [current_project]
update_ip_catalog
set_property ip_output_repo e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/hdl/spectrum_feb10_xadc_hdmi_wrapper.v
add_files E:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/spectrum_feb10_xadc_hdmi.bd
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_processing_system7_0_0/spectrum_feb10_xadc_hdmi_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_clk_wiz_0_0/spectrum_feb10_xadc_hdmi_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_clk_wiz_0_0/spectrum_feb10_xadc_hdmi_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_clk_wiz_0_0/spectrum_feb10_xadc_hdmi_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xbar_0/spectrum_feb10_xadc_hdmi_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_rst_ps7_0_50M_0/spectrum_feb10_xadc_hdmi_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_rst_ps7_0_50M_0/spectrum_feb10_xadc_hdmi_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_rst_ps7_0_50M_0/spectrum_feb10_xadc_hdmi_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_auto_pc_0/spectrum_feb10_xadc_hdmi_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/spectrum_feb10_xadc_hdmi_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/constrs_1/imports/digilent-xdc-master/Zybo-Master.xdc
set_property used_in_implementation false [get_files E:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/constrs_1/imports/digilent-xdc-master/Zybo-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top spectrum_feb10_xadc_hdmi_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef spectrum_feb10_xadc_hdmi_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file spectrum_feb10_xadc_hdmi_wrapper_utilization_synth.rpt -pb spectrum_feb10_xadc_hdmi_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
