# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0.xci
# IP: The module: 'spectrum_feb10_xadc_hdmi_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spectrum_feb10_xadc_hdmi_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'spectrum_feb10_xadc_hdmi_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0.xci
# IP: The module: 'spectrum_feb10_xadc_hdmi_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spectrum_feb10_xadc_hdmi_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/spectrum_analyzer_feb9/spectrum_analyzer_feb9.srcs/sources_1/bd/spectrum_feb10_xadc_hdmi/ip/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0/spectrum_feb10_xadc_hdmi_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'spectrum_feb10_xadc_hdmi_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
